### PR TITLE
docs: Introducing Hooks

### PR DESCRIPTION
**Pull request by turdiyev**

### CODE REVIEW

**Comment by avocadowastaken** [comment]
> Introducing Hooks (@turdiyev) #1

You should update this issue #1 with the number of current PR
```diff
-  * [ ] Introducing Hooks
+  * [ ] Introducing Hooks (@turdiyev) #4
```

**Comment by avocadowastaken** [comment]
@turdiyev Is it work in progress?

**Comment by turdiyev** [comment]
> @turdiyev Is it work in progress?

Sorry, I don't get you. Do you mean does this PR reference to the issue?

**Comment by avocadowastaken** [comment]
@turdiyev it's not fully translated

**Comment by turdiyev** [comment]
> @turdiyev it's not fully translated

hmm, this file is too long to translate. It is in progress, but with onHold status ).

**Comment by avocadowastaken** [comment]
> It is in progress

That's the answer to my first question :) 

I add `[WIP]` prefix to PR name and unassigned myself from it. Assign me once you finish everything.

**Comment by turdiyev** [comment]
> > Introducing Hooks (@turdiyev) #1
> 
> You should update this issue #1 with the number of current PR
> 
> ```diff
> -  * [ ] Introducing Hooks
> +  * [ ] Introducing Hooks (@turdiyev) #4
> ```

But, it already referenced to issue. You can see logs: https://github.com/reactjs/uz.reactjs.org/issues/1

**Comment by avocadowastaken** [comment]
Please read #1 issue `For New Translators` and `For Maintainers` sections carefully

**Review by kuldoshev17 — DISMISSED** [review]

**Comment by turdiyev** [comment]
> Please read #1 issue `For New Translators` and `For Maintainers` sections carefully

Thanks. ok. i see.

**Review by avocadowastaken — APPROVED** [review]

**Comment by avocadowastaken** [comment]
@turdiyev is it ready to merge?

**Comment by turdiyev** [comment]
> @turdiyev is it ready to merge?

Yep

**Pull request merged**
